lab_item_ids  | lab_item_names
-5230  |  Sodium_Whole_Blood
-5226  |  Potassium
-5034  |  Calcium_Total
-5215  |  Calcium_Total
-5218  |  Chloride_Whole_Blood
-5047  |  Glucose
-5223  |  Glucose
-5212  |  Anion_Gap
-5213  |  Anion_Gap
-5235  |  pCO2
-5236  |  pCO2
-5256  |  tCO2(P)
-5097  |  Hematocrit
-5225  |  Hematocrit
-5059  |  Magnesium
-7023  |  whole_blood_Magnesium
-5072  |  Phosphate
-5224  |  Calculated_Bicarbonate_Whole_Blood
-5248  |  Bicarbonate
-5237  |  pH
-5238  |  pH
-5374  |  PH
-5386  |  pH
-5034  |  Calcium_Total
-5215  |  Calcium_Total
-5235  |  pCO2
-5236  |  pCO2
-5239  |  pO2
-5244  |  pO2
-5241  |  pO2(A)/FO2(I)
-5242  |  pO2(AT)
-5208  |  pO2(a/AT)
-5210  |  pO2(A-aT)
-5243  |  pO2(T)/FO2(I)
-5245  |  pO2(x)
-5114  |  MCHC
-5099  |  Hemoglobin
-5257  |  Hemoglobin
-5113  |  MCH
-5115  |  MCV
-5132  |  Red_Blood_Cells
-5110  |  Absolute_Lymphocyte_Count
-6316  |  Monocyte_Count
-5094  |  Neutrophils
-5006  |  Lymphocytes_Percent
-5111  |  Lymphocytes_Percent
-5503  |  Lymphocytes_Percent
-6317  |  Monocytes
-5005  |  Neutrophils_%
-5095  |  Neutrophils_%
-5511  |  Neutrophils_%
-5129  |  Platelet_Count
-5141  |  WBC_Count
-5024  |  Albumin
-5120  |  Mean_Platelet_Volume_(MPV)
-5136  |  RDW
-5002  |  Eosinophils
-6318  |  Eosinophil_Count
-5042  |  Bilirubin_Direct
-5075  |  Bilirubin_Total
-5255  |  Bilirubin_Total
-5002  |  Eosinophils
-6318  |  Eosinophil_Count
-5078  |  Protein_Total
-5025  |  Alkaline_Phosphatase
-5492  |  Basophils
-5493  |  Basophils_Count
-5626  |  C-Reactive_Protein
-5821  |  C-Reactive_Protein
-5038  |  Creatine_Kinase_(CK)
-5227  |  Lactate
-5174  |  INR(PT)
-5186  |  PT
-6890  |  PT
-5164  |  Fibrinogen_Functional
-5161  |  PTT
-6165  |  Thyroxine_(T4)_Free
-6183  |  Thyroxine_(T4)_Free
-6095  |  Thyroid_Stimulating_Hormone
-6193  |  Thyroid_Stimulating_Hormone
-6393  |  C12
-6393  |  C12
-6396  |  C14
-6395  |  C14:1
-6394  |  C14:2
-6397  |  C14-OH
-6399  |  C16
-6398  |  C16:1
-6400  |  C16:1-OH
-6401  |  C16-OH
-6405  |  C18
-6404  |  C18:1
-6406  |  C18:1-OH
-6403  |  C18:2
-5262  |  C3
-5263  |  C4
-6352  |  C5DC
-5153  |  Atypical_Lymphocytes
-6841  |  Atypical_Lymphocytes
-5141  |  WBC_Count
-6349  |  Acetyl-carnitine
-6348  |  CarnitineFree
-6334  |  Ammonia
-5832  |  CMV_antibody_assay_(IgG)
-6984  |  CMV_antibody_assay_(IgG)
-6098  |  CMV_antibody_assay_(IgM)
-6989  |  CMV_antibody_assay_(IgM)
-6340  |  citrulline
-5038  |  Creatine_Kinase_(CK)
-6338  |  Alanine
-5027  |  Amylase
-6339  |  Arginine
-6109  |  cooper
-5047  |  Glucose
-5223  |  Glucose
-6341  |  Glycine
-6342  |  Leucine
-6473  |  Lipase
-6796  |  Lipase
-6343  |  Methionine
-6344  |  Ornithine
-6345  |  Phenylalanine
-6419  |  Proline
-6346  |  Tyrosine
-6347  |  Valine
-5248  |  Bicarbonate
-5224  |  Calculated_Bicarbonate_Whole_Blood
-5235  |  pCO2
-5236  |  pCO2
-6065  |  EBV_antibody_IgG
-7003  |  EBV_antibody_IgG
-6625  |  EBV-EA_IgG
-6066  |  EBV_antibody_IgM
-7002  |  EBV_antibody_IgM
-6624  |  EBV-EA_IgM
-7006  |  EBV-EA_IgM
-6626  |  EBNA_lgG
-7005  |  EBNA_lgG
-6483  |  ABO_blood_typing
-6497  |  ABO_blood_typing_infants

